
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ThoriumModzhcn</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CalamityBardHealer">
      <HintPath>lib\CalamityBardHealer.dll</HintPath>
    </Reference>
    <Reference Include="RagnarokMod">
      <HintPath>lib\RagnarokMod_v1.5.2.dll</HintPath>
    </Reference>
    <Reference Include="RedemptionBardHealer">
      <HintPath>lib\RedemptionBardHealer.dll</HintPath>
    </Reference>
    <Reference Include="ThoriumMod">
      <HintPath>lib\ThoriumMod.dll</HintPath>
    </Reference>
    <Reference Include="ThoriumRework">
      <HintPath>lib\ThoriumRework.dll</HintPath>
    </Reference>
    <Reference Include="TigerForceLocalizationLib">
      <HintPath>lib\TigerForceLocalizationLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
